### ISSUE TITLE
Background color key doesn't work!!!

### ISSUE THREAD

**Issue by mdfateh** [tmmgn/react-native-material-snackbar#1]
This toast library works as i needed, just i am unable to change background through the specified method.

It returns black only even after changing in the code.
e.g.

```
Snackbar.show({
      title: 'Register Failed',
      duration: Snackbar.LENGTH_LONG,
      backgroundColor: 'red'
    });
```

**Comment by tmmgn** [comment]
Sorry to hear that, but unfortunately this library is not maintained anymore, i suggest you to pick another e.g. https://github.com/tmmgn/react-native-snackbar-reddit, its more customisable, faster and maintained atm
